version: '3.9'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - uploads:/app/uploads
    environment:
      - FLASK_ENV=development
      - POSTGRES_USER=flask
      - POSTGRES_PASSWORD=secretpassword
      - POSTGRES_DB=mydb
      - DATABASE_URL=postgresql://flask:secretpassword@db/mydb
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=flask
      - POSTGRES_PASSWORD=secretpassword
      - POSTGRES_DB=mydb
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
  uploads:
